server:
  port: 8082

spring:
  application:
    name: crop-order-service

  datasource:
    url: jdbc:mysql://localhost:3306/cropdeal_crops
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
