server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/cropdeal_user
    username: root
    password: Shubh28gaikwad@
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
